@startuml
title Project Management

actor Admin as "Project admin"
actor User as "Logged-in User"
participant Frontend 
participant Backend
database Database

User -> Frontend: Project title and visibility level entered
Frontend -> Backend: Title & visiblity level
Backend -> Database: Title & visibility level
alt Project title is unique
Database --> Backend: Project ID
Backend -> Database: Make user admin
Backend --> Frontend: Project ID
Frontend --> Admin: Redirect to newly created project
else Project title is not unique
Database --> Backend: Project name unique violation
Backend --> Frontend: 422 status code
Frontend --> User: Display "project title already taken" message
end

Admin -> Frontend: Add project adminstrator/viewer by username
Frontend -> Backend: New admin/viewer username
alt User found
    Database --> Backend: Success
    Backend --> Frontend: 201 status code
    Frontend --> Admin: New user shown in list of project admins/viewers
else User not found
    Database --> Backend: Specified user not found
    Backend --> Frontend: 404 status code
    Frontend --> Admin: Display "username not found" message
end

Admin -> Frontend: Add new environment
alt Environment is unique
    Frontend -> Backend: Project ID & environment
    Backend -> Database: Project ID & environment
    Backend --> Frontend: 201 status code
    Frontend --> Admin: New environment shown in list of environments
else Environment already exists
    Frontend --> Admin: Display "environment already exists" message
end


Admin -> Frontend: Delete project button clicked
Frontend --> Admin: "Are you sure?" prompt shown
opt "Yes" clicked
    Frontend -> Backend: Delete request w/ project ID
    Backend -> Database: Delete project
    Backend --> Frontend: 200 status code
    Frontend --> Admin: Redirect to home page
end

@enduml