@startuml
title Log In, Log Out & Sign Up Flow

actor User
participant Frontend 
participant Backend
database Database

User -> Frontend: Username and password entered
opt Password is insufficiently secure (sign up)
    Frontend --> User: Display "password is insufficient" message
end

Frontend -> Backend: Username and password
Backend -> Database: User entity with hashed password

alt Succesful sign up/login
    Database --> Backend: User ID
    Backend --> Frontend: Session cookie
    Frontend --> User: Redirect to last viewed page
else Username is not unique (sign up)
    Database --> Backend: Username field unique violation
    Backend --> Frontend: 422 status code
    Frontend --> User: Display "username has already been taken" message
else Username or password incorrect (sign in)
    Database --> Backend: User w/ specified username and password not found
    Backend --> Frontend: 401 status code
    Frontend --> User: Display "username or password incorrect" message
end

User -> Frontend: "Log Out" button clicked
Frontend --> User: User is logged out

@enduml