name: "Test & Lint"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  backend:
    name: backend
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: ${{ env.working-directory }}
    
      - name: Test
        working-directory: ${{ env.working-directory }}
        run: go test -v
  
  frontend:
    name: frontend
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install 
          dir: ${{ env.working-directory }}
      
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint 
          dir: ${{ env.working-directory }}

      - name: Unit test
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit 
          dir: ${{ env.working-directory }}